title: Otero-Leon Lab
description: Designing data-driven decision models to improve healthcare systems and patient outcomes.
url: ""
baseurl: ""
markdown: kramdown
permalink: pretty
collections:
  people:
    output: false
  publications:
    output: false
  research:
    output: false
  news:
    output: false
  talks:
    output: false
  teaching:
    output: false
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: people
    values:
      layout: default
  - scope:
      path: ""
      type: publications
    values:
      layout: default
plugins: []
